### ISSUE TITLE
error: 1093 You can't specify target table 'phpcr_nodes' for update in FROM clause 

### ISSUE THREAD

**Issue by laurentiuc** [jackalope/jackalope-doctrine-dbal#317] opened 2016-01-24 14:39 UTC
Hello, 

Having this error while trying to move a node. the exceptions happen here

```
vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/Client.php line 1847 
```

any help is much appreciated. 

thanks,
laurentiu

**Comment by dbu** [comment] 2016-02-08 11:17
looking at the [mysql documentation](http://dev.mysql.com/doc/refman/5.6/en/update.html), it seems the problem is "You cannot update a table and select from the same table in a subquery."

this makes me wonder why all these tests about moving nodes work out fine: https://github.com/phpcr/phpcr-api-tests/blob/master/tests/Writing/MoveMethodsTest.php - are we missing something in there? maybe not deep enough children? do things fail for you locally and on the server? or only on the server?

if i interpret https://docs.travis-ci.com/user/database-setup/#MySQL-5.6 correctly,travis-ci is using mysql 5.5.

can you play around with the jackalope functional tests and try to reproduce the problem? having a failing test would really help to narrow down the issue. if you could do a pull request on phpcr-api-tests where you add to the MoveMethodsTest or to the fixtures for that test that leads to the exception i can have a look if i find solutions.

**Comment by laurentiuc** [comment] 2016-02-08 11:44
Yes, I've read the documentation about MySQL also and tried to replicate the query directly in mysql but without any luck no matter how I'm changing the query based on their suggestions. 

- this is happening on client's server (MySQL 5.5 Unix) + on my local server (I have 5.7.9 (on OS X))
- the nodes I'm trying to rename have 1 children only but they are on 5 / 6 depth level within the whole tree. 

ok, going to get the functional tests and reproduce the problem.

**Comment by dbu** [comment] 2016-02-08 11:58
my request for the tests is that we do have a similar mysql version on
travis-ci so the same problem should occur for us as well. wondering if
there could be a reason the same query never actually happens in our tests.

**Comment by markcollister** [comment] 2016-12-19 20:42
I just confirmed that this is an issue with vanilla Mysql, but MariaDB seems to support the query

**Comment by dbu** [comment] 2016-12-20 07:14
okay. is there any chance you can reproduce this with a new test case in phpcr-api-tests? the test suite contains some tests for doing move operations and the like, maybe you can take one of them as a starting point. if we can reproduce the problem on travis-ci with a test, i can try to find a workaround.

**Comment by markcollister** [comment] 2016-12-21 00:01
cool thanks, i’ll have a go in the new year when i’m back on the computer

**Comment by dbu** [comment] 2016-12-21 07:46
> cool thanks, i’ll have a go in the new year when i’m back on the computer

alright, enjoy your holidays!

**Comment by dbu** [comment] 2017-01-19 07:48
any luck with this one @markcollister ?

**Comment by markcollister** [comment] 2017-01-19 20:30
i had time for a quick look, i’d isolated the issue to

https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L1828

that sql run’s on my instance of MariaDB but not vanilla mysql

**Comment by dbu** [comment] 2017-04-07 09:04
so this only happens with very old versions of mysql? afaik travis-ci is running plain mysql not mariadb.

**Comment by markcollister** [comment] 2017-04-07 21:15
That was mysql 5.7.10, so old-ish :) . I'm not sure the test's covered this interaction with the database

**Comment by dbu** [comment] 2017-04-17 09:48
we have lots of tests with moving nodes around: https://github.com/phpcr/phpcr-api-tests/blob/master/tests/Writing/MoveMethodsTest.php 

do you see that there is something missing there that would reproduce the problem?

**Comment by dbu** [comment] 2023-03-04 10:51
closing as it only affects outdated mysql versions.

**Closed by dbu** 2023-03-04 10:51 UTC
